select * from cars;
select * from salespersons;
select * from sales;

-- 1. What are the details of all cars purchased in the year 2022?

SELECT 
    c.*
FROM
    cars c
        JOIN
    sales s ON c.car_id = s.car_id
WHERE
    YEAR(s.purchase_date) = 2022;

-- 2. What is the total number of cars sold by each salesperson?

SELECT 
    sp.name, COUNT(s.salesman_id) AS car_sold
FROM
    salespersons sp
        JOIN
    sales s ON s.salesman_id = sp.salesman_id
GROUP BY sp.name;

-- 3. What is the total revenue generated by each salesperson?

SELECT 
    salespersons.name,
    SUM(cars.cost_$) AS total_revenue_generated
FROM
    sales
        INNER JOIN
    salespersons ON sales.salesman_id = salespersons.salesman_id
        INNER JOIN
    cars ON sales.car_id = cars.car_id
GROUP BY salespersons.name;

-- 4. What are the details of the cars sold by each salesperson?

SELECT 
    salespersons.name, cars.*
FROM
    sales
        INNER JOIN
    salespersons ON sales.salesman_id = salespersons.salesman_id
        INNER JOIN
    cars ON sales.car_id = cars.car_id
ORDER BY salespersons.name;

-- 5. What is the total revenue generated by each car type?

SELECT 
    cars.type, SUM(cars.cost_$) AS total_revenue_generated
FROM
    sales
        INNER JOIN
    cars ON sales.car_id = cars.car_id
GROUP BY cars.type;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT 
    sales.sale_id, cars.make, cars.type, cars.style, cars.cost_$
FROM
    sales
        INNER JOIN
    cars ON sales.car_id = cars.car_id
        INNER JOIN
    salespersons ON sales.salesman_id = salespersons.salesman_id
WHERE
    YEAR(sales.purchase_date) = 2021
        AND salespersons.name = 'Emily Wong';

-- 7. What is the total revenue generated by the sales of hatchback cars?

SELECT 
    SUM(cars.cost_$) AS total_revenue_generated
FROM
    sales
        INNER JOIN
    cars ON sales.car_id = cars.car_id
WHERE
    cars.style = 'Hatchback';

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT 
    SUM(cars.cost_$) AS total_revenue_generated
FROM
    sales
        INNER JOIN
    cars ON sales.car_id = cars.car_id
WHERE
    YEAR(sales.purchase_date) = 2022
        AND cars.style = 'SUV';

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT 
    salespersons.name,
    salespersons.city,
    COUNT(*) AS total_cars_sold
FROM
    sales
        INNER JOIN
    salespersons ON sales.salesman_id = salespersons.salesman_id
WHERE
    YEAR(sales.purchase_date) = 2023
GROUP BY salespersons.name , salespersons.city
ORDER BY COUNT(*) DESC
LIMIT 1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT 
    salespersons.name,
    salespersons.age,
    SUM(cars.cost_$) AS total_revenue_generated
FROM
    sales
        INNER JOIN
    cars ON sales.car_id = cars.car_id
        INNER JOIN
    salespersons ON sales.salesman_id = salespersons.salesman_id
WHERE
    YEAR(sales.purchase_date) = 2022
GROUP BY salespersons.name , salespersons.age
ORDER BY SUM(cars.cost_$) DESC
LIMIT 1;
